### PR TITLE
[BugFix] content-length

### PR DESCRIPTION
**Pull request by xepa**
- Remove trimming the message it mutates what the user sent (and could add to spam score)
- Remove the extra content for the message, this means we can also remove the +2

### CODE REVIEW

**Comment by xepa** [comment]
Strange works for me on SA 3.4.0 .. lemme go check

**Comment by arp242** [comment]
The message needs to end with `\r\n`, otherwise SpamAssassin will never stop reading from the connection (it doesn't know when the line ends otherwise).

So if the message you sent already ends with `\r\n` it will probably work, but if it doesn't you get the error from the test.

I'm fine with either always appending `\r\n`, or only  when the message doesn't end with `\r\n`. Would be good to add a test for both scenarios though, SpamAssassin is rather finicky with stuff like this.

**Comment by xepa** [comment]
Yea noticed .. as all my test emails are all passing this test, the problem with always appending \r\n it that it might break some checks encryption/signing and the likes will probably break.  Not sure what your use case is but it might better be left up to the user to pass in that extra \r\n, most probably they will scan email and that already contains a ending \r\n

**Comment by arp242** [comment]
It has always added `\r\n` since I forked from the original, I didn't add that myself (I just copied it), so I don't have a specific use-case in mind.

My concern with removing this is that passing in the wrong data will just block the connection, which is *very* confusing behaviour. You could actually starve servers with connections quite easily by sending data that doesn't end in `\r\n`.

Is there any problem with doing something like this at the start of `write()`? I think that should give us the best of both?

```
if !strings.HasSuffix(msg, "\r\n") {
    message += "\r\n"
}
```

**Comment by xepa** [comment]
Yea I was thinking the same for the HasSuffix part but I realised that converting the message string to an io.Reader might throw a spanner in the works there ;(

Ok figured it out .. as SA is an email scanner it expects an email like body after the "headers" of SA
`<header lines \r\n terminated>\r\n<body \r\n terminated>`
So 
`\r\n\r\n`, `\r\nBODY\r\n` or `KEY: VALUE\r\n\r\nBODY\r\n` are examples of valid messages

when sending just the `Message\r\n\r\n` like in the tests my SA thinks that Message is an actual header and not a body part, check the result of a Headers check

**Comment by xepa** [comment]
@Carpetsmoker as discussed I have a pull ready that will change the message to a io.Reader, unfortunately it depends on this bugfix.  Any chance you have time to pull it, or if there are any changes that you would like, please let me know.

**Comment by arp242** [comment]
Thanks @xepa, looking forward to that.

As I mentioned, I'm not sure that it's a good idea to just remove this. It's not inconceivable that someone uses this in a larger application where the trailing `\r\n`s get lost, and the connection just hanging is very confusing behaviour!

I think the below patch is a better approach to this; I know this will be a bit more difficult to do with `io.Reader`, but I don't think it's impossible either (I haven't seen your patch, so can't offer any suggestions as how to do that yet).

This is one of those small details that's the difference between an "adequate" and "excellent" library :-)

---

```
diff --git i/sa_test.go w/sa_test.go
index ad57d7d..d49e6bf 100644
--- i/sa_test.go
+++ w/sa_test.go
@@ -81,6 +81,26 @@ func TestSALearn(t *testing.T) {
 	}
 }
 
+func TestSANoTrailingNewline(t *testing.T) {
+	client := New(addr, 0)
+
+	r, err := client.Check(context.Background(), "woot", nil)
+	if err != nil {
+		t.Fatal(err)
+	}
+	if r == nil {
+		t.Fatal("r is nil")
+	}
+
+	r, err = client.Check(context.Background(), "Subject: woot\r\n\r\nwoot", nil)
+	if err != nil {
+		t.Fatal(err)
+	}
+	if r == nil {
+		t.Fatal("r is nil")
+	}
+}
+
 func TestSACheck(t *testing.T) {
 	client := New(addr, 0)
 	r, err := client.Check(context.Background(), "\r\nPenis viagra\r\n", nil)
diff --git i/spamc.go w/spamc.go
index b772686..b263d9c 100644
--- i/spamc.go
+++ w/spamc.go
@@ -98,6 +98,12 @@ func (c *Client) write(
 		return err
 	}
 
+	// Make the sure message always ends in \r\n, if it doesn't SA will just
+	// keep reading from the connection and it will block until it timouts.
+	if !strings.HasSuffix(message, "\r\n") {
+		message += "\r\n"
+	}
+
 	// Always add Content-length header.
 	err = tp.PrintfLine("Content-length: %v", len(message))
 	if err != nil {
diff --git i/spamc_test.go w/spamc_test.go
index 8c89246..44a0f38 100644
--- i/spamc_test.go
+++ w/spamc_test.go
@@ -21,16 +21,16 @@ func TestWrite(t *testing.T) {
 	}{
 		{
 			"CMD", "Message", Header{HeaderUser: []string{"xx"}},
-			"CMD SPAMC/1.5\r\nContent-length: 7\r\nUser: xx\r\n\r\nMessage",
+			"CMD SPAMC/1.5\r\nContent-length: 9\r\nUser: xx\r\n\r\nMessage\r\n",
 			"",
 		},
 		{
 			"CMD", "Message", nil,
-			"CMD SPAMC/1.5\r\nContent-length: 7\r\n\r\nMessage",
+			"CMD SPAMC/1.5\r\nContent-length: 9\r\n\r\nMessage\r\n",
 			"",
 		},
 		{"", "Message", nil, "", "empty command"},
-		{"CMD", "", nil, "CMD SPAMC/1.5\r\nContent-length: 0\r\n\r\n", ""},
+		{"CMD", "", nil, "CMD SPAMC/1.5\r\nContent-length: 2\r\n\r\n\r\n", ""},
 	}
 
 	for i, tc := range cases {
```

**Comment by xepa** [comment]
I am working on refactoring the string message to io.Reader, I am also taking into account the necessity to prevent stalling spamassassin.  I will let you know when this is ready, for the time being I would suggest that this pull be closed.

**Comment by arp242** [comment]
I pushed my above patch and merged that. That will improve over the current behaviour and it adds a test for it.

> I am working on refactoring the string message to io.Reader

Alright :+1: Feel free to just open a PR with your work in progress. Doesn't need to be perfect from the get-go.

Also note that everything in `old.go` will soon be removed. I rewrote a bunch of code from there already, and need to finish up the rest. It's not worth refactoring any of that code.

**Pull request merged**
